DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
    UserID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UserName VARCHAR(255),
    Email VARCHAR(255),
    Password_Hash VARCHAR(10000),
    Contact_Num VARCHAR(20),
    Createed_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Last_Login TIMESTAMP,
    Total_Games INT DEFAULT 0,
    Total_Wins INT DEFAULT 0,
    Highest_Score INT DEFAULT 0
);

CREATE TABLE Questions (
    QuetionID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Question_Text TEXT NOT NULL,
    Difficulty TINYINT NOT NULL COMMENT '1: Easy, 2: Medium, 3:Hard',
    Category VARCHAR(50) NOT NULL COMMENT 'History, Players, Stats, WS',
    Createed_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Times_Used INT DEFAULT 0,
    Times_Answered_Correctly INT DEFAULT 0,
    GridPosition VARCHAR(5),
);

CREATE TABLE Game (
    GameID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Started_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Ended_At TIMESTAMP NULL
    Max_Players INT DEFAULT 8,
);

CREATE TABLE Game_Players (
    Game_PlayerID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CONSTRAINT FK_UserID FOREIGN KEY (UserID)
    REFERENCES Users(UserID) ON DELETE CASCADE,
    CONSTRAINT FK_GameID FOREIGN KEY (GameID)
    REFERENCES Game(GameID) ON DELETE CASCADE
);

CREATE TABLE Game_Questions (
    Game_QuestionID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CONSTRAINT FK_QuestionID FOREIGN KEY (QuestionID)
    REFERENCES Questions(QuestionID) ON DELETE CASCADE,
    CONSTRAINT FK_GameID FOREIGN KEY (GameID)
    REFERENCES Game(GameID) ON DELETE CASCADE
)